import { createContext, useContext, useState, type ReactNode } from "react";

type Language = "el" | "en";

const translations = {
  el: {
    // Header
    explore: "Εξερεύνηση",
    more: "Περισσότερα",
    signIn: "Σύνδεση",
    signOut: "Αποσύνδεση",
    dashboard: "Πίνακας Ελέγχου",
    admin: "Διαχείριση",
    partnerRegister: "Εγγραφή Επιχείρησης",
    // Categories
    accommodation: "Διαμονή",
    carRental: "Ενοικίαση Αυτοκινήτου",
    motoRental: "Ενοικίαση Μηχανής",
    restaurants: "Φαγητό & Ποτό",
    activities: "Δραστηριότητες",
    // Hero
    heroTitle: "Η #1 επιλογή σας στα ταξίδια",
    searchPlaceholder: "Δοκιμάστε 'Σύρος'...",
    suitableFor: "Κατάλληλο για:",
    exploreCta: "Εξερευνήστε",
    carMoto: "Car & Moto",
    foodDrink: "Φαγητό & Ποτό",
    // Category section
    exploreCategories: "Εξερευνήστε Κατηγορίες",
    findBestServices: "Βρείτε τις καλύτερες υπηρεσίες για το ταξίδι σας",
    hotelsVillas: "Ξενοδοχεία, βίλες & διαμερίσματα",
    carsForEveryNeed: "Αυτοκίνητα για κάθε ανάγκη",
    bikesScooters: "Μηχανές & σκούτερ",
    tasteWorth: "Γεύσεις που αξίζει να δοκιμάσετε",
    // Auth
    login: "Σύνδεση",
    register: "Εγγραφή",
    loginToAccount: "Συνδεθείτε στον λογαριασμό σας",
    createAccount: "Δημιουργήστε νέο λογαριασμό",
    name: "Όνομα",
    yourName: "Το όνομά σας",
    email: "Email",
    password: "Κωδικός",
    forgotPassword: "Ξεχάσατε τον κωδικό;",
    pleaseWait: "Παρακαλώ περιμένετε...",
    noAccount: "Δεν έχετε λογαριασμό; Εγγραφείτε",
    hasAccount: "Έχετε ήδη λογαριασμό; Συνδεθείτε",
    registerAsBusiness: "Εγγραφή ως Επιχείρηση →",
    // Footer
    footerDescription: "Η #1 πλατφόρμα ανακάλυψης ταξιδιωτικών υπηρεσιών στην Ελλάδα.",
    categories: "Κατηγορίες",
    contact: "Επικοινωνία",
    allRights: "All rights reserved.",
    footerAboutUs: "Σχετικά με εμάς",
    footerPrivacyPolicy: "Πολιτική Απορρήτου",
    footerPartners: "Συνεργάτες",
    footerRegister: "Εγγραφείτε",
    // Listing
    contactTitle: "Επικοινωνία",
    noListingsFound: "Δεν βρέθηκαν καταχωρίσεις σε αυτήν την κατηγορία.",
    listingNotFound: "Η καταχώριση δεν βρέθηκε",
    // Language
    language: "Γλώσσα",
    // Visitor Dashboard
    vFavorites: "Αγαπημένα",
    vMessages: "Μηνύματα",
    vAccount: "Λογαριασμός",
    vAccountDetails: "Στοιχεία Λογαριασμού",
    vMenu: "Μενού",
    vNoFavorites: "Δεν έχετε αγαπημένες καταχωρίσεις ακόμα.",
    vExploreFavorites: "Εξερευνήστε τις κατηγορίες και πατήστε ♥ για να αποθηκεύσετε.",
    vNoMessages: "Δεν έχετε στείλει μηνύματα ακόμα.",
    vTo: "Προς",
    vMyAccount: "Ο Λογαριασμός μου",
    vMyAccountDesc: "Ο λογαριασμός σας στο About Traveller",
    // Listing Form
    lfEditListing: "Επεξεργασία Καταχώρισης",
    lfNewListing: "Νέα Καταχώριση",
    lfBusinessName: "Επωνυμία Επιχείρησης",
    lfBusinessNamePlaceholder: "π.χ. Ξενοδοχείο Αιγαίο",
    lfCategory: "Κατηγορία",
    lfSelectCategory: "Επιλέξτε κατηγορία",
    lfType: "Είδος",
    lfSelectType: "Επιλέξτε είδος",
    lfRecommendedFor: "Προτείνεται για",
    lfRooms: "Δωμάτια",
    lfBeds: "Κρεβάτια",
    lfPersons: "Άτομα",
    lfCapacity: "Χωρητικότητα (άτομα)",
    lfSeats: "Θέσεις επιβατών",
    lfPriceFrom: "Τιμή από (€)",
    lfPriceTo: "Τιμή έως (€)",
    lfDescription: "Περιγραφή",
    lfDescriptionPlaceholder: "Περιγράψτε την επιχείρησή σας...",
    lfPhone: "Τηλέφωνο",
    lfLocation: "Τοποθεσία",
    lfPhotos: "Φωτογραφίες",
    lfUploading: "Ανέβασμα...",
    lfSelectPhotos: "Επιλέξτε φωτογραφίες (max 5MB)",
    lfPolicyAccept: "Αποδέχομαι την πολιτική περιεχομένου. Απαγορεύεται spam, πορνογραφικό υλικό, παράνομες υπηρεσίες ή παραπλανητικές πληροφορίες.",
    lfSaving: "Αποθήκευση...",
    lfUpdate: "Ενημέρωση",
    lfCreate: "Δημιουργία",
    lfPolicyRequired: "Πρέπει να αποδεχθείτε την πολιτική περιεχομένου",
    lfUpdated: "Η καταχώριση ενημερώθηκε!",
    lfCreated: "Η καταχώριση δημιουργήθηκε!",
    lfError: "Κάτι πήγε στραβά",
    lfFileTooBig: "υπερβαίνει τα 5MB",
    lfPhotosUploaded: "φωτογραφία(ες) ανέβηκαν",
    lfUploadError: "Σφάλμα κατά το ανέβασμα",
    // Admin Dashboard
    adTitle: "Admin Dashboard",
    adSubtitle: "Πλήρης διαχείριση πλατφόρμας",
    adListings: "Καταχωρίσεις",
    adUsers: "Χρήστες",
    adSubscriptions: "Συνδρομές",
    adActiveSubscriptions: "Ενεργές Συνδρομές",
    adHiddenListings: "Κρυφές Καταχωρίσεις",
    adNoListings: "Δεν υπάρχουν καταχωρίσεις.",
    adNoUsers: "Δεν υπάρχουν χρήστες.",
    adNoSubscriptions: "Δεν υπάρχουν συνδρομές.",
    adApprove: "Έγκριση",
    adHide: "Απόκρυψη",
    adReject: "Απόρριψη",
    adDelete: "Διαγραφή",
    adDeleteConfirm: "Σίγουρα θέλετε να διαγράψετε το",
    adDeleted: "Η καταχώριση διαγράφηκε",
    adStatusChanged: "Η κατάσταση άλλαξε σε",
    adActive: "Ενεργή",
    adPending: "Εκκρεμεί",
    adHidden: "Κρυφή",
    adRejected: "Απορρίφθηκε",
    adPeriod: "Περίοδος",
    adNotStarted: "Δεν έχει ξεκινήσει",
    adGracePeriod: "Grace period μέχρι",
    adSubActive: "Ενεργή",
    adSubPastDue: "Εκκρεμής",
  },
  en: {
    explore: "Explore",
    more: "More",
    signIn: "Sign in",
    signOut: "Sign out",
    dashboard: "Dashboard",
    admin: "Admin",
    partnerRegister: "Business Registration",
    accommodation: "Accommodation",
    carRental: "Car Rental",
    motoRental: "Moto Rental",
    restaurants: "Food & Drink",
    activities: "Activities",
    heroTitle: "Your #1 choice in travel",
    searchPlaceholder: "Try 'Syros'...",
    suitableFor: "Suitable for:",
    exploreCta: "#Explore",
    carMoto: "Car & Moto",
    foodDrink: "Food & Drink",
    exploreCategories: "Explore Categories",
    findBestServices: "Find the best services for your trip",
    hotelsVillas: "Hotels, villas & apartments",
    carsForEveryNeed: "Cars for every need",
    bikesScooters: "Bikes & scooters",
    tasteWorth: "Flavours worth tasting",
    login: "Login",
    register: "Register",
    loginToAccount: "Login to your account",
    createAccount: "Create a new account",
    name: "Name",
    yourName: "Your name",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    pleaseWait: "Please wait...",
    noAccount: "Don't have an account? Register",
    hasAccount: "Already have an account? Login",
    registerAsBusiness: "Register as Business →",
    footerDescription: "The #1 travel service discovery platform in Greece.",
    categories: "Categories",
    contact: "Contact",
    allRights: "All rights reserved.",
    footerAboutUs: "About Us",
    footerPrivacyPolicy: "Privacy Policy",
    footerPartners: "Partners",
    footerRegister: "Register!",
    contactTitle: "Contact",
    noListingsFound: "No listings found in this category.",
    listingNotFound: "Listing not found",
    language: "Language",
    // Visitor Dashboard
    vFavorites: "Favorites",
    vMessages: "Messages",
    vAccount: "Account",
    vAccountDetails: "Account Details",
    vMenu: "Menu",
    vNoFavorites: "You don't have any favorites yet.",
    vExploreFavorites: "Explore categories and tap ♥ to save.",
    vNoMessages: "You haven't sent any messages yet.",
    vTo: "To",
    vMyAccount: "My Account",
    vMyAccountDesc: "Your account at About Traveller",
    // Listing Form
    lfEditListing: "Edit Listing",
    lfNewListing: "New Listing",
    lfBusinessName: "Business Name",
    lfBusinessNamePlaceholder: "e.g. Aegean Hotel",
    lfCategory: "Category",
    lfSelectCategory: "Select category",
    lfType: "Type",
    lfSelectType: "Select type",
    lfRecommendedFor: "Recommended for",
    lfRooms: "Rooms",
    lfBeds: "Beds",
    lfPersons: "Persons",
    lfCapacity: "Capacity (persons)",
    lfSeats: "Passenger seats",
    lfPriceFrom: "Price from (€)",
    lfPriceTo: "Price to (€)",
    lfDescription: "Description",
    lfDescriptionPlaceholder: "Describe your business...",
    lfPhone: "Phone",
    lfLocation: "Location",
    lfPhotos: "Photos",
    lfUploading: "Uploading...",
    lfSelectPhotos: "Select photos (max 5MB)",
    lfPolicyAccept: "I accept the content policy. Spam, pornographic material, illegal services or misleading information is prohibited.",
    lfSaving: "Saving...",
    lfUpdate: "Update",
    lfCreate: "Create",
    lfPolicyRequired: "You must accept the content policy",
    lfUpdated: "Listing updated!",
    lfCreated: "Listing created!",
    lfError: "Something went wrong",
    lfFileTooBig: "exceeds 5MB",
    lfPhotosUploaded: "photo(s) uploaded",
    lfUploadError: "Upload error",
    // Admin Dashboard
    adTitle: "Admin Dashboard",
    adSubtitle: "Full platform management",
    adListings: "Listings",
    adUsers: "Users",
    adSubscriptions: "Subscriptions",
    adActiveSubscriptions: "Active Subscriptions",
    adHiddenListings: "Hidden Listings",
    adNoListings: "No listings found.",
    adNoUsers: "No users found.",
    adNoSubscriptions: "No subscriptions found.",
    adApprove: "Approve",
    adHide: "Hide",
    adReject: "Reject",
    adDelete: "Delete",
    adDeleteConfirm: "Are you sure you want to delete",
    adDeleted: "Listing deleted",
    adStatusChanged: "Status changed to",
    adActive: "Active",
    adPending: "Pending",
    adHidden: "Hidden",
    adRejected: "Rejected",
    adPeriod: "Period",
    adNotStarted: "Not started yet",
    adGracePeriod: "Grace period until",
    adSubActive: "Active",
    adSubPastDue: "Past due",
  },
} as const;

type Translations = Record<keyof typeof translations.el, string>;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "el",
  setLang: () => {},
  t: translations.el,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("el");

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
};
