ALTER TABLE public.listings
ADD COLUMN IF NOT EXISTS capacity integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rooms integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS beds integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS price_from numeric DEFAULT NULL;